-- Cloud Resource Manager - Supabase Schema
-- Run order: 1-schema.sql, 2-policies.sql, 3-functions.sql, 4-seed.sql
-- How to run: Paste this file in Supabase SQL editor and execute in your project's database.
-- Notes:
-- - Uses auth.users (Supabase) as the source of user identities.
-- - Do not paste any secrets here. This file is safe for version control.

-- Create schema for app objects (use public for simplicity)
-- Enums
create type provider_type as enum ('aws','azure','gcp');
create type resource_type as enum ('vm','db','storage','network','other');
create type resource_status as enum ('creating','running','stopped','deleting','error');
create type notification_severity as enum ('info','warning','critical');
create type audit_action as enum ('create','update','delete','login','logout','grant','revoke');
create type invoice_status as enum ('draft','open','paid','void','uncollectible');

-- Profiles (1:1 with auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text generated always as (coalesce((auth.jwt() -> 'email')::text, null)) stored, -- optional convenience (may be null)
  role text not null default 'user', -- 'admin' or 'user'; mirrored to app_metadata/user_metadata in frontend
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Cloud providers a user has connected/authorized
create table if not exists public.providers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider provider_type not null,
  account_id text,          -- external cloud account id
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, provider, account_id)
);

-- Managed resources across providers
create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider provider_type not null,
  name text not null,
  type resource_type not null,
  region text,
  status resource_status not null default 'creating',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_resources_user on public.resources(user_id);
create index if not exists idx_resources_provider on public.resources(provider);
create index if not exists idx_resources_name on public.resources using gin (to_tsvector('simple', coalesce(name,'')));

-- Monitoring metrics (time-series)
create table if not exists public.monitoring_metrics (
  id bigint generated by default as identity primary key,
  resource_id bigint not null references public.resources(id) on delete cascade,
  metric_name text not null,    -- e.g., cpu_utilization, memory_usage
  metric_value numeric not null,
  unit text,                    -- e.g., percent, bytes
  timestamp timestamptz not null default now()
);
create index if not exists idx_monitoring_metrics_resource_ts on public.monitoring_metrics(resource_id, timestamp desc);

-- Notifications
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  message text,
  severity notification_severity not null default 'info',
  read boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_notifications_user_created on public.notifications(user_id, created_at desc);

-- Billing snapshots (aggregated per user per month)
create table if not exists public.billing_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  year int not null,
  month int not null check (month between 1 and 12),
  total_amount numeric(12,2) not null default 0,
  projected_amount numeric(12,2) not null default 0,
  savings_amount numeric(12,2) not null default 0,
  currency text not null default 'USD',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, year, month)
);

-- Invoices (for UI listing)
create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null default (now()::date),
  amount numeric(12,2) not null default 0,
  status invoice_status not null default 'draft',
  created_at timestamptz not null default now()
);
create index if not exists idx_invoices_user_date on public.invoices(user_id, date desc);

-- Admin audit logs
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action audit_action not null,
  entity text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_audit_logs_created on public.audit_logs(created_at desc);

-- Optional support for adminService (users_view, user_roles)
create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin','user'))
);

create or replace view public.users_view as
select
  u.id,
  u.email,
  coalesce(ur.role, 'user') as role,
  'active'::text as status
from auth.users u
left join public.user_roles ur on ur.user_id = u.id;

-- Triggers to maintain updated_at
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end; $$;

drop trigger if exists set_updated_at_profiles on public.profiles;
create trigger set_updated_at_profiles
before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_providers on public.providers;
create trigger set_updated_at_providers
before update on public.providers
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_resources on public.resources;
create trigger set_updated_at_resources
before update on public.resources
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_billing on public.billing_snapshots;
create trigger set_updated_at_billing
before update on public.billing_snapshots
for each row execute procedure public.set_updated_at();
